-- Aarush Pizza Oven — Supabase schema
-- Run in Supabase SQL Editor or via CLI: supabase db push

create extension if not exists "pgcrypto";

-- Admins (link Supabase Auth users here after first signup)
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.business_settings (
  id int primary key default 1 check (id = 1),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id text primary key,
  title text not null,
  description text not null,
  icon text not null default 'Wrench',
  popular boolean not null default false,
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.spare_parts (
  id text primary key,
  name text not null,
  category text not null,
  description text not null,
  compatible text not null,
  image_src text not null,
  image_alt text not null,
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  src text not null,
  caption text not null,
  alt text not null,
  sort_order int not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.enquiries (
  id uuid primary key default gen_random_uuid(),
  subject_type text,
  subject_title text,
  customer_name text,
  customer_phone text,
  area text,
  oven_type text,
  issue text,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

alter table public.admin_users enable row level security;
alter table public.business_settings enable row level security;
alter table public.services enable row level security;
alter table public.spare_parts enable row level security;
alter table public.gallery_items enable row level security;
alter table public.enquiries enable row level security;

-- admin_users: only admins can read list; service role manages inserts
create policy "admins read admin_users"
  on public.admin_users for select
  to authenticated
  using (public.is_admin());

-- business_settings
create policy "public read business_settings"
  on public.business_settings for select
  to anon, authenticated
  using (true);

create policy "admins manage business_settings"
  on public.business_settings for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- services
create policy "public read services"
  on public.services for select
  to anon, authenticated
  using (true);

create policy "admins manage services"
  on public.services for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- spare_parts
create policy "public read spare_parts"
  on public.spare_parts for select
  to anon, authenticated
  using (true);

create policy "admins manage spare_parts"
  on public.spare_parts for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- gallery_items
create policy "public read gallery_items"
  on public.gallery_items for select
  to anon, authenticated
  using (true);

create policy "admins manage gallery_items"
  on public.gallery_items for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- enquiries: anyone can submit; admins read
create policy "public insert enquiries"
  on public.enquiries for insert
  to anon, authenticated
  with check (true);

create policy "admins read enquiries"
  on public.enquiries for select
  to authenticated
  using (public.is_admin());

-- Seed defaults (idempotent)
insert into public.business_settings (id, data)
values (
  1,
  '{
    "phone": "",
    "whatsapp": "",
    "openingHours": "Mon - Sat: 9:00 AM - 8:00 PM (Subject to confirmation)"
  }'::jsonb
)
on conflict (id) do nothing;
